"""empty message

Revision ID: 0314efd61303
Revises: 
Create Date: 2021-08-23 23:35:26.240546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0314efd61303'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_champions_id'), 'champions', ['id'], unique=False)
    op.create_table('skins',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('trimmed_image_url', sa.String(), nullable=True),
    sa.Column('full_image_url', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('champion_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skins_id'), 'skins', ['id'], unique=False)
    op.create_table('price_history',
    sa.Column('skin_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], ),
    sa.PrimaryKeyConstraint('skin_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_index(op.f('ix_skins_id'), table_name='skins')
    op.drop_table('skins')
    op.drop_index(op.f('ix_champions_id'), table_name='champions')
    op.drop_table('champions')
    # ### end Alembic commands ###
