"""Add 'is_available' and 'is_on_sale'

Revision ID: 282e09f96776
Revises: 0314efd61303
Create Date: 2021-08-26 13:51:23.615763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282e09f96776'
down_revision = '0314efd61303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('is_available', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('price_history', sa.Column('is_on_sale', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'is_on_sale')
    op.drop_column('price_history', 'is_available')
    # ### end Alembic commands ###
