"""Initial migration

Revision ID: 78c2284225d0
Revises: 
Create Date: 2021-09-14 20:33:51.472108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c2284225d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_champions'))
    )
    with op.batch_alter_table('champions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_champions_id'), ['id'], unique=False)

    op.create_table('skins',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trimmed_image_url', sa.String(), nullable=True),
    sa.Column('full_image_url', sa.String(), nullable=True),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champions.id'], name=op.f('fk_skins_champion_id_champions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skins'))
    )
    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skins_id'), ['id'], unique=False)

    op.create_table('price_history',
    sa.Column('skin_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_on_sale', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['skin_id'], ['skins.id'], name=op.f('fk_price_history_skin_id_skins')),
    sa.PrimaryKeyConstraint('skin_id', 'date', name=op.f('pk_price_history'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    with op.batch_alter_table('skins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skins_id'))

    op.drop_table('skins')
    with op.batch_alter_table('champions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_champions_id'))

    op.drop_table('champions')
    # ### end Alembic commands ###
