"""Add trigger for price and sale_price

Revision ID: 963c003e0059
Revises: 0314efd61303
Create Date: 2021-08-24 17:08:58.711031

"""
from alembic import op
import sqlalchemy as sa
from app.models import update_prices_ddl, drop_update_prices_ddl

# revision identifiers, used by Alembic.
revision = '963c003e0059'
down_revision = '0314efd61303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skins', sa.Column('update_date', sa.Date(), nullable=True))
    update_prices_ddl(target=None, bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skins', 'update_date')
    drop_update_prices_ddl(target=None, bind=op.get_bind())
    # ### end Alembic commands ###
